import { clientId } from './client-id.js';
import { useEffect, useRef, useState } from 'react';
import { z } from 'zod';
import { ActionSchema, ComposerInitialSchema, CorrectionsListSchema, ConversationChangesSchema, ConversationEventSchema, ConversationListSchema, ConversationNoticeSchema, ConversationPublicSchema, ConversationReadSchema, ProjectsListSchema, type Action, type DecisionRecord, type Effort, type LedgerEvent, type Project } from '@jevellan/core/client';
import { api, empty } from './api.js';
import { ProjectForm } from './projects.js';
import { waitForProjectSetup } from './project-setup.js';
import { queuedRefresh } from './refresh.js';
import { changeComposerDraft, ComposerChoices } from './composer-choices.js';
import { EvidenceLink, EvidencePanel, type EvidenceTarget } from './evidence.js';
import { Markdown, Modal, dateTime, useTask, type PageProps } from './components.js';

type View = z.infer<typeof ConversationPublicSchema>;
type Step = View['stretches'][number];
const stateLabel = (state: string) => ({ 'waiting-for-you': 'Waiting for you', 'running': 'Running', 'done': 'Done', 'cancelled': 'Cancelled', 'blocked': 'Blocked', 'idle': 'Ready' })[state] ?? state;
const actionLabel = (action: string) => action === 'ask-you' ? 'Ask you' : action.split('-').map((word) => word[0]!.toUpperCase() + word.slice(1)).join(' ');
const object = (value: unknown): Record<string, unknown> => value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : {};
const relativeTime = (at: string) => { const minutes = Math.max(0, Math.floor((Date.now() - Date.parse(at)) / 60_000)); return minutes < 1 ? 'Just now' : minutes < 60 ? `${minutes} min ago` : minutes < 1440 ? `${Math.floor(minutes / 60)} hr ago` : `${Math.floor(minutes / 1440)} days ago`; };

export function ConversationSidebar({ data, navigate, onError, selected }: Pick<PageProps, 'data' | 'navigate' | 'onError'> & { selected: string }) {
  const [conversations, setConversations] = useState<z.infer<typeof ConversationListSchema>['conversations']>([]); const [projects, setProjects] = useState<Project[]>([]); const [filter, setFilter] = useState('All');
  useEffect(() => {
    let stopped = false; let running = false; const controller = new AbortController();
    const load = async () => { if (running) return; running = true; try { const [list, projects] = await Promise.all([api('/api/conversations', ConversationListSchema, 'GET', undefined, { signal: controller.signal, waitForHub: true }), api('/hub/projects', ProjectsListSchema, 'GET', undefined, { signal: controller.signal, waitForHub: true })]); if (!stopped) { setConversations(list.conversations); setProjects(projects.projects.map((row) => row.project)); } } catch (error) { if (!stopped) onError(error); } finally { running = false; } };
    const changed = () => void load(); window.addEventListener('jevellan-conversation-updated', changed);
    void load(); const timer = setInterval(changed, 5000); return () => { stopped = true; controller.abort(); clearInterval(timer); window.removeEventListener('jevellan-conversation-updated', changed); };
  }, [onError, selected]);
  const visible = conversations.filter((entry) => filter === 'All' || filter === 'Running' && entry.state === 'running' || filter === 'Waiting for you' && ['waiting-for-you', 'blocked'].includes(entry.state) || filter === 'Done' && ['done', 'cancelled'].includes(entry.state));
  return <><div className="filter-chips" aria-label="Conversation filters">{['All', 'Running', 'Waiting for you', 'Done'].map((label) => <button key={label} className={label === filter ? 'selected' : ''} onClick={() => setFilter(label)}>{label}</button>)}</div><div className="conversation-list">{!conversations.length ? <p className="empty-conversations">No conversations yet. Start one to put your agents to work.</p> : !visible.length ? <p className="empty-conversations">No conversations in this view.</p> : visible.map((entry) => <button className={`conversation-row ${selected === `/conversations/${entry.id}` ? 'selected' : ''}`} key={entry.id} onClick={() => navigate(`/conversations/${entry.id}`)}><strong>{entry.title}</strong><span>{projects.find((project) => project.id === entry.projectId)?.name ?? entry.projectId} · {data.devices.devices.find((device) => device.id === entry.ownerDeviceId)?.name ?? entry.ownerDeviceId}</span><span><i className={`state-dot state-${entry.state}`}/>{stateLabel(entry.state)} · {relativeTime(entry.updatedAt)}</span></button>)}</div></>;
}

export function NewConversation(props: PageProps & { embedded?: boolean }) {
  const [projects, setProjects] = useState<Project[]>([]); const [projectId, setProjectId] = useState(''); const [message, setMessage] = useState(''); const task = useTask(props.onError);
  const [waitingForSetup, setWaitingForSetup] = useState(false); const [addingProject, setAddingProject] = useState(false);
  const [choices, setChoices] = useState(() => ComposerInitialSchema.parse({ schema: 'composer-initial-v1', once: {}, pins: {} }));
  const pending = useRef<{ signature: string; id: string; clientMessageId: string } | undefined>(undefined);
  const device = props.data.devices.devices.find((entry) => entry.id === props.data.devices.currentDeviceId)!;
  useEffect(() => { const controller = new AbortController(); void api('/hub/projects', ProjectsListSchema, 'GET', undefined, { signal: controller.signal, waitForHub: true }).then((value) => { setProjects(value.projects.map((row) => row.project)); setProjectId(value.projects[0]?.project.id ?? ''); }).catch(props.onError); return () => controller.abort(); }, [props.onError]);
  const project = projects.find((entry) => entry.id === projectId); const available = project?.paths[device.id] && (!project.allowedDevices || project.allowedDevices.includes(device.id));
  return <>{!props.embedded && <><h1>New conversation</h1><p className="intro">Give your agents a project and an objective.</p></>}{!props.data.accounts.length && <p className="notice">Add an account to Claude Code or Codex first. <button className="text-button" onClick={() => props.navigate('/settings/runtimes')}>Open Runtimes →</button></p>}{!props.data.jev.saved && <p className="notice">Add your Jev key in Settings → Decisions. Until then you pick each step yourself.</p>}
    <form className="card new-conversation-form" onSubmit={(event) => { event.preventDefault(); void task.run(async (signal) => {
      const signature = JSON.stringify({ projectId, message, choices }); if (pending.current?.signature !== signature) pending.current = { signature, id: `conversation_${clientId()}`, clientMessageId: `message_${clientId()}` };
      try { await waitForProjectSetup(projectId, signal, () => setWaitingForSetup(true)); }
      finally { setWaitingForSetup(false); }
      const created = await api('/api/conversations', ConversationPublicSchema, 'POST', { schema: 'start-conversation-v1', id: pending.current.id, clientMessageId: pending.current.clientMessageId, projectId, title: message.split('\n')[0]!.slice(0, 100), message, ...(Object.keys(choices.once).length || Object.keys(choices.pins).length ? { choices } : {}) }, { signal, waitForHub: true }); props.navigate(`/conversations/${created.conversation.id}`);
    }); }}><label>Project<select required value={projectId} onChange={(event) => setProjectId(event.target.value)}><option value="" disabled>{projects.length ? 'Choose a project' : 'Add a project first'}</option>{projects.map((entry) => <option value={entry.id} key={entry.id}>{entry.name}</option>)}</select></label><div className="project-picker-actions"><span className="muted small-text">On {device.name}</span><button type="button" className="text-button" onClick={() => setAddingProject(true)}>＋ Add project</button></div>{project && !available && <p className="notice">{project.name} isn’t set up on {device.name}. Add its path in Settings → Projects, or switch device.</p>}<label><span className="sr-only">Message</span><textarea required rows={4} placeholder="What should we build or fix?" value={message} onChange={(event) => setMessage(event.target.value)}/></label><details className="composer-options"><summary>Next step settings <span>{Object.keys(choices.once).length || Object.keys(choices.pins).length ? 'Custom' : 'Auto'}</span></summary><ComposerChoices once={choices.once} pins={choices.pins} config={props.data.config.configuration['x-jevellan']} actions={ActionSchema.options.filter((action) => action !== 'integrate' && action !== 'done' && (action !== 'test' || !!project?.testCommand))} disabled={task.busy} change={(field, value, mode) => setChoices((current) => changeComposerDraft(current, field, value, mode))}/></details><button disabled={task.busy || !available || !props.data.accounts.length || !message.trim()}>{task.busy ? 'Starting…' : 'Start'}</button></form>
    {waitingForSetup && <p role="status">Finishing project setup…</p>}
    {addingProject && <ProjectForm {...props} row={undefined} knownPublic={false} close={() => setAddingProject(false)} saved={async signal => { const result = await api('/hub/projects', ProjectsListSchema, 'GET', undefined, { signal, waitForHub: true }); const added = result.projects.find(row => !projects.some(project => project.id === row.project.id)); setProjects(result.projects.map(row => row.project)); if (added) setProjectId(added.project.id); setAddingProject(false); props.message('Project added.'); }}/>}
  </>;
}

export function ConversationPage({ id, ...props }: PageProps & { id: string }) {
  const [view, setView] = useState<View>(); const [events, setEvents] = useState<LedgerEvent[]>([]); const [connected, setConnected] = useState(false);
  const followedPoint = useRef(false);
  useEffect(() => {
    if (followedPoint.current) return;
    const point = new URLSearchParams(window.location.search).get('stretch'); if (!point || !/^[1-9][0-9]*$/.test(point)) return;
    const element = document.getElementById(`stretch-${point}`); if (!element) return;
    followedPoint.current = true; element.scrollIntoView({ block: 'start' }); element.focus({ preventScroll: true });
  }, [events, view]);
  const [correcting, setCorrecting] = useState<Step>();
  const [projects, setProjects] = useState<Project[]>([]); const [settling, setSettling] = useState(false);
  const [editingConversation, setEditingConversation] = useState<'rename' | 'finish'>();
  const [message, setMessage] = useState(''); const [why, setWhy] = useState<DecisionRecord>(); const [changes, setChanges] = useState<z.infer<typeof ConversationChangesSchema>>(); const [content, setContent] = useState<EvidenceTarget>();
  const task = useTask(props.onError); const input = useRef<HTMLTextAreaElement>(null); const messageId = useRef(`message_${clientId()}`);
  useEffect(() => { if (view) window.dispatchEvent(new Event('jevellan-conversation-updated')); }, [view?.conversation.id, view?.conversation.state, view?.conversation.title]);
  useEffect(() => { void api('/hub/projects', ProjectsListSchema).then((value) => setProjects(value.projects.map((entry) => entry.project))).catch(props.onError); }, [props.onError]);
  useEffect(() => {
    let timer: ReturnType<typeof setTimeout> | undefined;
    const refresh = queuedRefresh(signal => api(`/api/conversations/${id}`, ConversationPublicSchema, 'GET', undefined, { signal }), setView, props.onError);
    void refresh.request(); const stream = new EventSource(`/api/conversations/${id}/events`);
    stream.onopen = () => setConnected(true); stream.onerror = () => setConnected(false);
    stream.addEventListener('conversation', (event: MessageEvent<string>) => {
      try { const value = ConversationEventSchema.parse(JSON.parse(event.data)); setEvents((previous) => previous.some((entry) => entry.id === value.event.id) ? previous : [...previous, value.event].sort((a, b) => a.id - b.id)); clearTimeout(timer); timer = setTimeout(() => void refresh.request(), 40); }
      catch (error) { stream.close(); props.onError(error); }
    });
    return () => { refresh.stop(); clearTimeout(timer); stream.close(); };
  }, [id, props.onError]);
  const submit = (kind: 'message' | 'note') => task.run(async () => { if (!message.trim()) return; const value = await api(`/api/conversations/${id}/messages`, ConversationPublicSchema, 'POST', { schema: 'conversation-message-v1', clientMessageId: messageId.current, text: message, kind }); messageId.current = `message_${clientId()}`; setView(value); setMessage(''); });
  const read = (ref: string, title: string, stretch?: number, source?: 'step' | 'working-tree', output = false) => setContent({ ref, title, stretch, source, output });
  if (!view) return <p className="muted">Loading conversation…</p>;
  const device = props.data.devices.devices.find((entry) => entry.id === view.conversation.ownerDeviceId); const running = view.busy || view.conversation.state === 'running'; const plan = view.conversation.work?.latestPlanRef;
  const project = projects.find((entry) => entry.id === view.conversation.projectId);
  const settlementTarget = view.conversation.work ?? view.closedWorks.at(-1);
  const latestSettlement = view.settlements.filter((entry) => entry.workId === settlementTarget?.id).at(-1);
  const canSettle = !!settlementTarget && settlementTarget.closedAs !== 'done' && (!!view.conversation.work || !latestSettlement || latestSettlement.status !== 'completed' || latestSettlement.retained);
  const kept = !view.conversation.work && canSettle;
  const checkpointBlock = view.checkpointBlocks.filter((entry) => entry.workId === settlementTarget?.id).at(-1);
  const finishing = view.finishes.find((entry) => entry.status !== 'completed');
  return <div className="conversation-page"><div className="section-heading conversation-heading"><h1><button className="conversation-title" title="Rename conversation" onClick={() => setEditingConversation('rename')}>{view.conversation.title}</button></h1><div className="actions">{running && <button className="secondary" disabled={task.busy} onClick={() => void task.run(async () => setView(await api(`/api/conversations/${id}/cancel`, ConversationPublicSchema, 'POST', empty)))}>Cancel</button>}<details className="conversation-menu"><summary aria-label="Conversation menu">⋯</summary><div><button onClick={(event) => { event.currentTarget.closest('details')?.removeAttribute('open'); setEditingConversation('rename'); }}>Rename</button><button disabled={!!finishing || !!view.conversation.outcome} onClick={(event) => { event.currentTarget.closest('details')?.removeAttribute('open'); setEditingConversation('finish'); }}>Finished outside Jevellan</button></div></details></div></div><p className="muted small-text">{project?.name ?? view.conversation.projectId} · {device?.name} · {running ? 'Working' : stateLabel(view.conversation.state)}</p>{!connected && <p className="notice" role="status">Reconnecting…</p>}
    {running && <ConversationActivity view={view} events={events}/>}
    {view.conversation.outcome && <section className="notice"><strong>Finished outside Jevellan</strong>{view.conversation.outcome.reason && <p>{view.conversation.outcome.reason}</p>}</section>}
    {finishing?.status === 'blocked' && <section className="card"><h2>Finish outside Jevellan</h2><p>{finishing.reason}</p><button disabled={task.busy} onClick={() => void task.run(async () => setView(await api(`/api/conversations/${id}/finish-outside`, ConversationPublicSchema, 'POST', finishing.request)))}>Retry finishing</button></section>}
    <div className="timeline" aria-label="Conversation timeline">{events.map((event) => {
      if (event.type === 'user-message' || event.type === 'note') return <article className="user-message" key={event.id}><strong>{event.type === 'note' ? 'Your note' : 'You'}</strong><p>{String(object(event.data).text ?? '')}</p></article>;
      if (event.type === 'stretch-start') { const step = view.stretches.find((entry) => entry.n === event.stretch); if (!step) return null; return <StepBlock key={event.id} step={step} view={view} events={events.filter((entry) => entry.stretch === step.n)} props={props} correct={() => setCorrecting(step)} why={() => setWhy(view.decisions.find((entry) => entry.id === step.decisionId))} changes={() => void task.run(async () => setChanges(await api(`/api/conversations/${id}/changes/${step.n}`, ConversationChangesSchema)))} read={(pointer, title) => read(pointer, title, step.n)}/>; }
      const notice = ConversationNoticeSchema.safeParse(event.data); if (notice.success) return <p key={event.id} className={notice.data.kind === 'error' ? 'error' : 'notice'}>{notice.data.text}</p>;
      return null;
    })}</div>
    {view.pause && <p className="notice">{view.pause.reason}</p>}
    {!running && view.externalWait && !checkpointBlock && !finishing && <div className="actions"><button disabled={task.busy || view.busy} onClick={() => void task.run(async () => setView(await api(`/api/conversations/${id}/retry-external`, ConversationPublicSchema, 'POST', { schema: 'retry-external-activity-v1', waitId: view.externalWait!.id, generation: view.conversation.generation })))}>Retry</button></div>}
    {!running && view.decisionWait && !view.pause?.guard && !checkpointBlock && <div className="actions decision-recovery"><button className="secondary" disabled={task.busy} onClick={() => void task.run(async () => setView(await api(`/api/conversations/${id}/resume`, ConversationPublicSchema, 'POST', { schema: 'resume-decision-v1', generation: view.conversation.generation })))}>Try automatic again</button>{[...new Set(view.decisionWait.reasons.flatMap((reason) => reason.accountIds))].map((accountId) => <button key={accountId} className="text-button" onClick={() => props.navigate(`/settings/runtimes?account=${encodeURIComponent(accountId)}`)}>Review {props.data.accounts.find((entry) => entry.account.id === accountId)?.account.label ?? accountId}</button>)}</div>}
    {!running && checkpointBlock && <section className="card"><h2>Changes need your review</h2><p>Check the files before accepting them as this work’s changes.</p><button disabled={task.busy} onClick={() => void task.run(async () => setChanges(await api(`/api/conversations/${id}/changes/${checkpointBlock.stretch}`, ConversationChangesSchema)))}>Review changes</button></section>}
    {!running && view.redos.filter((entry) => entry.status === 'blocked' && (entry.workId === (view.conversation.work ?? view.closedWorks.at(-1))?.id || entry.followingWorkId && entry.followingWorkId === view.conversation.work?.id && entry.workId === view.closedWorks.at(-1)?.id)).map((entry) => <RetryRedo key={entry.id} entry={entry} view={view} update={setView} onError={props.onError}/>)}
    {!running && plan && props.data.config.configuration['x-jevellan'].guards.pauseAfterPlan && view.conversation.work?.approvedPlanRef !== plan && <div className="actions plan-actions"><button disabled={task.busy} onClick={() => void task.run(async () => setView(await api(`/api/conversations/${id}/approve-plan`, ConversationPublicSchema, 'POST', { schema: 'plan-approval-v1', generation: view.conversation.generation, ref: plan })))}>Go ahead</button><button className="secondary" onClick={() => { setMessage('Change the plan: '); input.current?.focus(); }}>Change the plan</button></div>}
    {!running && !finishing && view.conversation.work && !view.pause?.guard && !checkpointBlock && <ManualPicker view={view} props={props} update={setView}/>}
    {kept && <p className="notice">Settle this work’s changes before starting another request.</p>}
    <form className="composer card" onSubmit={(event) => { event.preventDefault(); if (!kept && !finishing) void submit('message'); }}><label><span className="sr-only">Message</span><textarea ref={input} rows={2} value={message} onChange={(event) => setMessage(event.target.value)} placeholder={running ? 'Add a note or steer this work…' : 'What would you like to do next?'}/></label><details className="composer-options"><summary>Next step settings <span>{Object.keys(view.conversation.once).length || Object.keys(view.conversation.pins).length ? 'Custom' : 'Auto'}</span></summary><ComposerChoices once={view.conversation.once} pins={view.conversation.pins} config={props.data.config.configuration['x-jevellan']} actions={view.conversation.work ? view.allowed : ActionSchema.options.filter((action) => action !== 'integrate' && action !== 'done' && (action !== 'test' || !!project?.testCommand))} disabled={task.busy || !!finishing} change={(field, value, mode) => void task.run(async () => setView(await api(`/api/conversations/${id}/choices`, ConversationPublicSchema, 'POST', { schema: 'composer-choice-v1', clientRequestId: `choice_${clientId()}`, generation: view.conversation.generation, field, value, mode })))}/></details><div className="actions"><button disabled={task.busy || kept || !!finishing || !message.trim()}>{running ? 'Send correction' : 'Send'}</button>{running && <button type="button" className="secondary" disabled={task.busy || kept || !!finishing || !message.trim()} onClick={() => void submit('note')}>Add note</button>}{!running && !finishing && canSettle && <button type="button" className="secondary" disabled={!project} onClick={() => setSettling(true)}>{view.conversation.work ? 'Close this work' : 'Settle kept changes'}</button>}</div></form>
    {editingConversation && <EditConversation kind={editingConversation} view={view} update={setView} close={() => setEditingConversation(undefined)} onError={props.onError}/>}
    {settling && settlementTarget && project && <SettleWork view={view} project={project} workId={settlementTarget.id} update={setView} close={() => setSettling(false)} onError={props.onError}/>}
    {correcting && <ChangeStep step={correcting} view={view} external={project?.branchPolicy === 'external'} props={props} update={setView} close={() => setCorrecting(undefined)}/>}
    {why && <Why decision={why} props={props} close={() => setWhy(undefined)}/>}
    {changes && <Modal title={`Changes · step ${changes.stretch}`} close={() => setChanges(undefined)}><div className="changed-file-list" aria-label="Changed files">{changes.files.map((file) => <p key={`${file.source}/${file.path}`}><EvidenceLink value={file.path} file open={(ref) => read(ref, file.path, changes.stretch, file.source)}/><span className="muted small-text"> · {file.source === 'step' ? 'Recorded step' : 'Working copy'}</span></p>)}</div><Diff text={changes.diff}/>{changes.uncommitted && <><h3>Uncommitted changes</h3><Diff text={changes.uncommitted}/></>}{changes.recovery && <AcceptChanges changes={changes} view={view} update={setView} close={() => setChanges(undefined)} refresh={() => api(`/api/conversations/${id}/changes/${changes.stretch}`, ConversationChangesSchema).then(setChanges)} onError={props.onError}/>}{changes.evidence.length > 0 && <><h3>Agent evidence</h3>{changes.evidence.map((item, i) => <p key={i}>{item.kind}: <EvidenceLink value={item.ref} file={item.kind === 'file' || item.kind === 'screenshot'} open={(ref) => read(ref, item.note ?? ref, changes.stretch)}/>{item.note ? ` — ${item.note}` : ''}</p>)}</>}<h3>Jevellan verification</h3>{!changes.verifications.length && <p className="muted">No verification receipt yet.</p>}{changes.verifications.map((receipt) => <div className="verification-receipt" key={receipt.id}><strong>{receipt.passed && receipt.headStable && (receipt.treeClean || receipt.worktreeBefore === receipt.worktreeAfter && !!receipt.worktreeBefore) ? 'Passed' : 'Failed'}</strong><p><code>{receipt.command}</code><br/>Commit <code>{receipt.commit}</code></p><button className="text-button" onClick={() => void read(receipt.outputRef, 'Verification output', changes.stretch, undefined, true)}>Read output</button></div>)}</Modal>}
    {content && <EvidencePanel key={JSON.stringify(content)} id={id} target={content} close={() => setContent(undefined)}/>}
  </div>;
}
const progressLabels = {
  preparing: ['Preparing your request', 'Checking the project and available accounts.'],
  deciding: ['Jev is choosing the next step', 'Classifying the request and selecting a model and effort.'],
  memory: ['Preparing context', 'Selecting relevant project memory for this step.'],
  starting: ['Starting the agent', 'The step is selected. Waiting for its first response.'],
  running: ['Agent is working', 'Responses and tool activity appear below as they arrive.'],
  saving: ['Saving this step', 'Checking changes and recording the handoff.'],
  verifying: ['Checking the result', 'Validating the work before marking it complete.'],
  publishing: ['Verifying and publishing', 'Running the final checks and saving the result.'],
} as const;
function ConversationActivity({ view, events }: { view: View; events: LedgerEvent[] }) {
  const [now, setNow] = useState(Date.now());
  useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, []);
  const step = view.stretches.findLast(entry => entry.status === 'running');
  const phase = view.progress?.phase ?? (step ? 'running' : 'preparing');
  const [title, description] = progressLabels[phase];
  const since = view.progress?.since ?? step?.startedAt ?? view.conversation.updatedAt;
  const elapsed = Math.max(0, Math.floor((now - Date.parse(since)) / 1000));
  const latestTool = step && events.findLast(event => event.stretch === step.n && event.type === 'tool-start');
  const tool = latestTool && object(latestTool.data);
  const pending = tool && !events.some(event => event.type === 'tool-end' && object(event.data).id === tool.id);
  return <section className="conversation-activity" aria-label="Current activity"><span className="activity-spinner" aria-hidden="true"/><div><strong role="status">{title}</strong><p>{phase === 'running' && pending ? `Using ${String(tool.name)}…` : description}</p></div><time aria-label="Time in this stage">{elapsed < 60 ? `${elapsed}s` : `${Math.floor(elapsed / 60)}m ${elapsed % 60}s`}</time></section>;
}
function EditConversation({ kind, view, update, close, onError }: { kind: 'rename' | 'finish'; view: View; update(value: View): void; close(): void; onError(error: unknown): void }) {
  const [value, setValue] = useState(kind === 'rename' ? view.conversation.title : ''); const task = useTask(onError);
  const original = useRef({ title: view.conversation.title, generation: view.conversation.generation });
  const pending = useRef<{ value: string; id: string } | undefined>(undefined);
  return <Modal title={kind === 'rename' ? 'Rename conversation' : 'Finished outside Jevellan'} close={close}><form onSubmit={(event) => { event.preventDefault(); void task.run(async () => {
    const text = value.trim(); if (pending.current?.value !== text) pending.current = { value: text, id: `${kind}_${clientId()}` };
    const body = kind === 'rename' ? { schema: 'rename-conversation-v1', clientRequestId: pending.current.id, previousTitle: original.current.title, title: text } : { schema: 'finish-outside-v1', clientRequestId: pending.current.id, generation: original.current.generation, ...(text ? { reason: text } : {}) };
    update(await api(`/api/conversations/${view.conversation.id}/${kind === 'rename' ? 'rename' : 'finish-outside'}`, ConversationPublicSchema, 'POST', body)); close();
  }); }}>{kind === 'rename' ? <label>Title<input required maxLength={200} autoFocus value={value} onChange={(event) => setValue(event.target.value)}/></label> : <><p>This stops the active step and keeps repository changes. Kept changes remain available to settle.</p><label>What made you finish elsewhere?<textarea rows={4} maxLength={2000} autoFocus value={value} onChange={(event) => setValue(event.target.value)}/><span className="muted small-text">Optional</span></label></>}<div className="form-actions"><button type="button" className="secondary" disabled={task.busy} onClick={close}>Cancel</button><button disabled={task.busy || kind === 'rename' && !value.trim()}>{task.busy ? 'Saving…' : kind === 'rename' ? 'Save title' : 'Mark finished'}</button></div></form></Modal>;
}
function AcceptChanges({ changes, view, update, close, refresh, onError }: { changes: z.infer<typeof ConversationChangesSchema>; view: View; update(value: View): void; close(): void; refresh(): Promise<void>; onError(error: unknown): void }) {
  const task = useTask(onError); const request = useRef<{ fingerprint: string; id: string } | undefined>(undefined);
  const review = changes.recovery!; const step = view.stretches.find((entry) => entry.n === changes.stretch)!;
  return <section className="card"><h3>Accept reviewed changes</h3><p>{review.mode === 'acknowledge' ? 'Continue acknowledges the files shown here. This project follows its own Git rules; Jevellan will not commit or push these changes.' : 'Continue saves the files shown here as this work’s checkpoint. You can then choose the next step or publish after verification.'}</p>{review.reason && <p className="notice">{review.reason}</p>}<div className="actions"><button disabled={task.busy || view.busy || !review.fingerprint || review.generation !== view.conversation.generation} onClick={() => void task.run(async () => {
    const fingerprint = review.fingerprint!;
    if (request.current?.fingerprint !== fingerprint) request.current = { fingerprint, id: `adopt_${clientId()}` };
    update(await api(`/api/conversations/${view.conversation.id}/adopt-changes`, ConversationPublicSchema, 'POST', { schema: 'adopt-changes-v1', clientRequestId: request.current.id, workId: step.workId, stretch: step.n, generation: review.generation, fingerprint })); close();
  })}>{task.busy ? 'Accepting…' : 'Continue'}</button><button className="secondary" disabled={task.busy} onClick={() => void task.run(refresh)}>Refresh changes</button></div></section>;
}
function RetryRedo({ entry, view, update, onError }: { entry: View['redos'][number]; view: View; update(value: View): void; onError(error: unknown): void }) {
  const task = useTask(onError); const request = useRef<{ generation: number; id: string } | undefined>(undefined);
  return <section className="card"><h2>Resume correction · step {entry.fromStretch}</h2><p>{entry.reason ?? 'Undo and redo did not finish.'}</p><p className="muted">Completed undo changes are kept. A redo step that already started will not run twice.</p><button disabled={task.busy} onClick={() => void task.run(async () => {
    if (request.current?.generation !== view.conversation.generation) request.current = { generation: view.conversation.generation, id: `retry_${clientId()}` };
    update(await api(`/api/conversations/${view.conversation.id}/retry-redo`, ConversationPublicSchema, 'POST', { schema: 'retry-redo-v1', clientRequestId: request.current.id, id: entry.id, generation: request.current.generation }));
    request.current = undefined;
  })}>{task.busy ? 'Resuming…' : 'Retry undo and redo'}</button></section>;
}
function SettleWork({ view, project, workId, update, close, onError }: { view: View; project: Project; workId: string; update(value: View): void; close(): void; onError(error: unknown): void }) {
  const [discard, setDiscard] = useState(false); const task = useTask(onError);
  const request = useRef<{ choice: string; id: string } | undefined>(undefined);
  const choose = (choice: 'publish' | 'keep' | 'discard') => task.run(async () => {
    if (request.current?.choice !== choice) request.current = { choice, id: `settlement_${clientId()}` };
    update(await api(`/api/conversations/${view.conversation.id}/settle`, ConversationPublicSchema, 'POST', { schema: 'settle-work-v1', clientRequestId: request.current.id, workId, generation: view.conversation.generation, choice })); close();
  });
  return <Modal title={discard ? 'Discard this work' : 'Close this work'} close={close}>{project.branchPolicy === 'external' ? <><p>This project follows its own git rules. Its files stay as they are.</p><button disabled={task.busy} onClick={() => void choose('keep')}>Close and keep changes</button></> : discard ? <><p>This resets this work’s unpublished code and memory checkpoints to where the work started. A recovery ref is saved first. Uncommitted files must be checkpointed before they can be discarded.</p><p>Anything outside the repository, such as databases, deployments or messages sent, is not undone.</p><div className="actions"><button disabled={task.busy} onClick={() => void choose('discard')}>Discard checkpoints</button><button className="secondary" disabled={task.busy} onClick={() => setDiscard(false)}>Back</button></div></> : <><p>Choose what happens to this work’s unpublished changes.</p><div className="settlement-choices"><div><button disabled={task.busy} onClick={() => void choose('publish')}>Publish</button><p>Verify the final checkpoint, bring in newer work from main, and publish.</p></div><div><button className="secondary" disabled={task.busy} onClick={() => void choose('keep')}>Keep them</button><p>Close the work and keep its changes. The checkout stays reserved while changes remain unsettled.</p></div><div><button className="secondary" disabled={task.busy} onClick={() => setDiscard(true)}>Discard…</button><p>Save a recovery ref, then reset unpublished checkpoints.</p></div></div></>}</Modal>;
}
function ManualPicker({ view, props, update }: { view: View; props: PageProps; update(value: View): void }) {
  const config = props.data.config.configuration['x-jevellan']; const models = config.menu.filter((model) => model.enabled && config.runtimes[model.runtime]?.enabled);
  const preferredModel = () => [view.conversation.once.modelId, view.conversation.pins.modelId, view.conversation.current?.modelId].find((id) => models.some((entry) => entry.id === id)) ?? models[0]?.id ?? '';
  const preferredEffort = () => view.conversation.once.effort ?? view.conversation.pins.effort ?? view.conversation.current?.effort ?? 'high';
  const [action, setAction] = useState<Action>(view.conversation.once.action ?? 'reply'); const [model, setModel] = useState(preferredModel); const [effort, setEffort] = useState<Effort>(preferredEffort); const [remember, setRemember] = useState(false); const task = useTask(props.onError);
  useEffect(() => { setAction(view.conversation.once.action ?? 'reply'); setModel(preferredModel()); setEffort(preferredEffort()); }, [view.conversation.once.action, view.conversation.once.modelId, view.conversation.once.effort, view.conversation.pins.modelId, view.conversation.pins.effort]);
  const planWaiting = config.guards.pauseAfterPlan && view.conversation.work?.latestPlanRef && view.conversation.work.approvedPlanRef !== view.conversation.work.latestPlanRef;
  const allowed = view.allowed.filter((entry) => !planWaiting || entry === 'plan'); const chosen = allowed.includes(action) ? action : allowed[0];
  return <form className="manual-picker card" onSubmit={(event) => { event.preventDefault(); void task.run(async () => update(await api(`/api/conversations/${view.conversation.id}/manual`, ConversationPublicSchema, 'POST', { schema: 'manual-step-v1', generation: view.conversation.generation, action: chosen, modelId: model || undefined, effort, remember }))); }}><h2>Pick the next step</h2><div className="manual-fields"><label>Action<select value={chosen} onChange={(event) => setAction(event.target.value as Action)}>{allowed.map((entry) => <option key={entry} value={entry}>{actionLabel(entry)}</option>)}</select></label><label>Model<select value={model} disabled={chosen === 'done'} onChange={(event) => setModel(event.target.value)}>{models.map((entry) => <option key={entry.id} value={entry.id}>{entry.label}</option>)}</select></label><label>Effort<select value={effort} disabled={chosen === 'done'} onChange={(event) => setEffort(event.target.value as Effort)}>{['low', 'medium', 'high', 'xhigh', 'max'].map((entry) => <option key={entry} value={entry}>{entry}</option>)}</select></label></div>{chosen === 'reply' && <label className="toggle"><input type="checkbox" checked={remember} onChange={(event) => setRemember(event.target.checked)}/>This request explicitly asks to remember something.</label>}<button disabled={task.busy || !chosen || chosen !== 'done' && !model}>{task.busy ? 'Starting…' : 'Continue'}</button></form>;
}
function StepBlock({ step, view, events, props, correct, why, changes, read }: { step: Step; view: View; events: LedgerEvent[]; props: PageProps; correct(): void; why(): void; changes(): void; read(pointer: string, title: string): void }) {
  const handoff = view.handoffs.find((entry) => entry.stretch === step.n); const model = props.data.config.configuration['x-jevellan'].menu.find((entry) => entry.id === step.modelId); const account = props.data.accounts.find((entry) => entry.account.id === step.accountId);
  const text = events.filter((entry) => entry.type === 'text').map((entry) => String(object(entry.data).delta ?? '')).join(''); const seconds = Math.max(0, Math.round((Date.parse(step.endedAt ?? new Date().toISOString()) - Date.parse(step.startedAt)) / 1000));
  const editable = step.status !== 'undone' && [view.conversation.work?.id, view.closedWorks.at(-1)?.id].includes(step.workId);
  const corrections = view.overrides.filter((entry) => entry.request.stretch === step.n);
  const decision = view.decisions.find((entry) => entry.id === step.decisionId);
  const findings = [...events.filter((event) => event.type === 'finding').map((event) => ({ claim: String(object(event.data).claim ?? ''), pointer: String(object(event.data).pointer ?? '') })), ...(handoff?.findings ?? [])].filter((finding, index, all) => all.findIndex((entry) => entry.claim === finding.claim && entry.pointer === finding.pointer) === index);
  return <article id={`stretch-${step.n}`} tabIndex={-1} className={`stretch-block card ${step.status === 'undone' ? 'undone' : ''}`}><h2>Step {step.n} · {actionLabel(step.action)}</h2><div className="model-chips"><button className="chip" disabled={!editable} onClick={correct} aria-label={`Change action for step ${step.n}`}>{actionLabel(step.action)}</button><button className="chip" disabled={!editable} onClick={correct} aria-label={`Change model for step ${step.n}`}>{model?.label ?? step.modelId}</button><button className="chip" disabled={!editable} onClick={correct} aria-label={`Change effort for step ${step.n}`}>{step.effortRequested === step.effortEffective ? step.effortEffective : `${step.effortRequested} → ${step.effortEffective}`}</button><span className="chip">{account?.account.label ?? step.accountId}</span><span className="chip">{props.data.devices.devices.find((entry) => entry.id === step.deviceId)?.name ?? step.deviceId}</span><span className="chip">{seconds}s · {step.usage.inputTokens + step.usage.outputTokens} tokens</span>{step.usage.costUsd !== undefined && <span className="chip">${step.usage.costUsd.toFixed(3)}{step.usage.costSource === 'estimated' ? ' estimated' : ''}</span>}<span className="chip">{step.status === 'undone' ? 'Undone' : step.status}</span>{corrections.map((entry) => <span className="chip" key={entry.id}>corrected: {entry.changes.map((change) => `${change.field} → ${change.to}`).join(', ')}</span>)}</div>{decision?.notices.filter((notice) => notice.kind === 'preferred-needs-login').map((notice, index) => <div className="notice" key={index}>{notice.text}{notice.accountId && <button className="text-button" onClick={() => props.navigate(`/settings/runtimes?account=${encodeURIComponent(notice.accountId!)}&login=1`)}>Log in</button>}</div>)}{text && (step.status === 'running' ? <Markdown onOpen={(ref) => read(ref, ref)}>{text}</Markdown> : <details className="step-transcript"><summary>Agent response</summary><Markdown onOpen={(ref) => read(ref, ref)}>{text}</Markdown></details>)}
    {events.some(entry => entry.type === 'tool-start') && <details className="tool-activity"><summary>Tool activity <span>{events.filter(entry => entry.type === 'tool-start').length} calls{events.some(entry => entry.type === 'tool-end' && object(entry.data).ok === false) ? ` · ${events.filter(entry => entry.type === 'tool-end' && object(entry.data).ok === false).length} failed` : ''}</span></summary>{events.filter((entry) => entry.type === 'tool-start').map((event) => { const tool = object(event.data); const end = events.find((entry) => entry.type === 'tool-end' && object(entry.data).id === tool.id); return <details className="tool-call" key={event.id}><summary>{String(tool.name ?? 'Tool')} · {end ? object(end.data).ok ? 'Done' : 'Failed' : 'Running'}</summary><pre>{JSON.stringify(tool.input, null, 2)}</pre>{[...new Set([object(tool.input).path, object(tool.input).file_path, object(tool.input).filePath].filter((value): value is string => typeof value === 'string'))].map((path) => <p className="tool-file" key={path}><EvidenceLink value={path} file open={(ref) => read(ref, ref)}/></p>)}{end && object(end.data).output !== undefined && <pre>{String(object(end.data).output)}</pre>}</details>; })}</details>}
    {handoff && <div className="handoff"><h3>Handoff · {handoff.status}</h3><Markdown onOpen={(ref) => read(ref, ref)}>{handoff.summary}</Markdown>{handoff.result?.type === 'plan' && <Plan id={view.conversation.id} pointer={handoff.result.ref} onError={props.onError} open={(ref) => read(ref, ref)}/>}{handoff.blockers.map((blocker, i) => <p className="notice" key={i}>{blocker}</p>)}{handoff.result && handoff.result.type !== 'plan' && <button className="text-button" onClick={() => read(handoff.result!.ref, 'Full result')}>Read full result</button>}</div>}
    {findings.length > 0 && <ul className="findings">{findings.map((finding, i) => <li key={i}>{finding.claim} <EvidenceLink value={finding.pointer} open={(ref) => read(ref, ref)}/></li>)}</ul>}
    <div className="actions"><button className="text-button" onClick={changes}>Changes</button><button className="text-button" onClick={why}>Why</button></div>
  </article>;
}
function ChangeStep({ step, view, external, props, update, close }: { step: Step; view: View; external: boolean; props: PageProps; update(value: View): void; close(): void }) {
  const models = props.data.config.configuration['x-jevellan'].menu;
  const [action, setAction] = useState(step.action); const [modelId, setModel] = useState(step.modelId); const [effort, setEffort] = useState(step.effortRequested); const [confirm, setConfirm] = useState(false);
  const task = useTask(props.onError); const request = useRef<{ signature: string; id: string } | undefined>(undefined);
  const choices = { ...(action !== step.action ? { action } : {}), ...(modelId !== step.modelId ? { modelId } : {}), ...(effort !== step.effortRequested ? { effort } : {}) };
  const changed = Object.keys(choices).length > 0;
  const submit = (mode: 'noted' | 'redo') => task.run(async () => {
    const body = { schema: 'correct-step-v1', generation: view.conversation.generation, stretch: step.n, mode, choices };
    const signature = JSON.stringify(body); if (request.current?.signature !== signature) request.current = { signature, id: `correction_${clientId()}` };
    update(await api(`/api/conversations/${view.conversation.id}/correct`, ConversationPublicSchema, 'POST', { ...body, clientRequestId: request.current.id })); close();
  });
  const choice = `${actionLabel(action)}, ${models.find((entry) => entry.id === modelId)?.label ?? modelId}, ${effort}`;
  return <Modal title="Change this step" close={close}>{external && <p className="notice">This project follows its own git rules. Undo changes the conversation history; repository files are kept.</p>}{confirm ? <><p>{external ? `This marks the steps from ${step.n} onwards undone in the conversation and redoes the step with ${choice}. Repository files are kept.` : `This undoes the code and memory changes from step ${step.n} onwards and redoes it with ${choice}. Anything outside the repository (databases, deployments, messages sent) is not undone.`}</p>{view.conversation.work && view.conversation.work.id !== step.workId && <p className="muted">This also undoes the newer open work. Its request and notes stay with the reopened work.</p>}<div className="actions"><button disabled={task.busy} onClick={() => void submit('redo')}>{task.busy ? 'Stopping and undoing…' : 'Undo and redo'}</button><button className="secondary" disabled={task.busy} onClick={() => setConfirm(false)}>Back</button></div></> : <><p>Step {step.n}</p><label>Action<select value={action} onChange={(event) => setAction(event.target.value as Action)}>{['reply', 'plan', 'implement', 'test', 'review', 'adversarial-review', 'ask-you', 'done', ...(step.action === 'integrate' ? ['integrate'] : [])].map((entry) => <option key={entry} value={entry} disabled={entry === 'integrate'}>{actionLabel(entry)}</option>)}</select></label><label>Model<select value={modelId} onChange={(event) => setModel(event.target.value)}>{models.map((entry) => <option key={entry.id} value={entry.id}>{entry.label}</option>)}</select></label><label>Effort<select value={effort} onChange={(event) => setEffort(event.target.value as Effort)}>{['low', 'medium', 'high', 'xhigh', 'max'].map((entry) => <option key={entry}>{entry}</option>)}</select></label><div className="actions"><button disabled={task.busy || !changed || action === 'integrate'} onClick={() => setConfirm(true)}>Override and undo</button><button className="secondary" disabled={task.busy || !changed} onClick={() => void submit('noted')}>Just override</button></div></>}</Modal>;
}
function Plan({ id, pointer, onError, open }: { id: string; pointer: string; onError(error: unknown): void; open(ref: string): void }) {
  const [content, setContent] = useState(''); useEffect(() => { let stopped = false; void api(`/api/conversations/${id}/read?pointer=${encodeURIComponent(pointer)}`, ConversationReadSchema).then((value) => { if (!stopped) setContent(typeof value.content === 'string' ? value.content : JSON.stringify(value.content, null, 2)); }).catch(onError); return () => { stopped = true; }; }, [id, pointer, onError]);
  return <div className="plan-result"><Markdown onOpen={open}>{content || 'Loading the full plan…'}</Markdown></div>;
}
function Diff({ text }: { text: string }) { return text ? <pre className="git-diff">{text.split('\n').map((line, index) => <span className={line.startsWith('+') ? 'addition' : line.startsWith('-') ? 'removal' : ''} key={index}>{line}{'\n'}</span>)}</pre> : <p className="muted">No checkpoint changes in this step.</p>; }
function WhyMemory({ memory }: Pick<DecisionRecord, 'memory'>) {
  if (!memory) return null;
  return <section className="why-memory" aria-label="Memory selection"><h3>Memory</h3><p className="muted small-text">{memory.source === 'search-rank' ? 'Selected by search rank.' : 'Selected by Jev.'}</p>
    <h4>Chosen memory</h4>{memory.chosen.length ? <ul aria-label="Chosen memory">{memory.chosen.map((note) => <li key={note}>{note}</li>)}</ul> : <p>No memory notes were selected.</p>}
    <details><summary>Candidates ({memory.candidates.length})</summary>{memory.candidates.length ? <ul aria-label="Memory candidates">{memory.candidates.map((note) => <li key={note}>{note}{memory.chosen.includes(note) ? ' · chosen' : ''}{memory.scores?.[note] === undefined ? '' : ` · score ${memory.scores[note]}`}</li>)}</ul> : <p>No candidate notes were found.</p>}</details>
  </section>;
}
function Why({ decision, props, close }: { decision: DecisionRecord; props: PageProps; close(): void }) {
  const [corrections, setCorrections] = useState<z.infer<typeof CorrectionsListSchema>['records']>();
  useEffect(() => {
    let active = true;
    void api(`/hub/overrides?ids=${encodeURIComponent(decision.correctionsShown.join(','))}`, CorrectionsListSchema).then((value) => { if (active) setCorrections(value.records); }).catch(props.onError);
    return () => { active = false; };
  }, [decision.id, props.onError]);
  const modelLabel = (id: string) => props.data.config.configuration['x-jevellan'].menu.find((model) => model.id === id)?.label ?? id;
  const accountLabel = (id: string) => props.data.accounts.find((entry) => entry.account.id === id)?.account.label ?? id;
  return <Modal title="Why this step" close={close}>
    <h3>Next step · {decision.action.source}</h3><p>{actionLabel(decision.action.chosen)}</p>
    {decision.action.guardReason && <p>{decision.action.guardReason}</p>}
    {decision.action.allowed.map((action) => <div className="why-option" key={action}><span>{actionLabel(action)}</span>{decision.action.probabilities?.[action] !== undefined && <><progress aria-label={`${actionLabel(action)} probability`} max={1} value={decision.action.probabilities[action]}/><span>{Math.round(decision.action.probabilities[action] * 100)}%</span></>}</div>)}
    {decision.model && <><h3>Model · {decision.model.source}</h3><p>{modelLabel(decision.model.chosen)}</p>{decision.model.keepCurrentP !== undefined && <p className="muted small-text">Suitability of the current model: {Math.round(decision.model.keepCurrentP * 100)}%.</p>}{decision.model.eligible.map((model) => <p className="muted small-text" key={model.modelId}>{modelLabel(model.modelId)}{model.p === undefined ? '' : ` · ${Math.round(model.p * 100)}%`}</p>)}{decision.model.preferredAny && <p>Preferred across enabled models: {modelLabel(decision.model.preferredAny.modelId)}.</p>}{decision.model.excluded.map((model) => <p key={model.modelId}>{modelLabel(model.modelId)}: {model.reason}</p>)}</>}
    {decision.effort && <><h3>Effort · {decision.effort.source}</h3><p>{decision.effort.requested} → {decision.effort.effective}{decision.effort.requested !== decision.effort.effective ? ' (nearest effort this model supports)' : ''}</p>{Object.entries(decision.effort.probabilities ?? {}).map(([effort, p]) => <div className="why-option" key={effort}><span>{effort}</span><progress aria-label={`${effort} effort probability`} max={1} value={p}/><span>{Math.round(p * 100)}%</span></div>)}</>}
    {decision.notices.map((notice, index) => <p key={index}>{notice.text}{notice.kind === 'preferred-needs-login' && notice.accountId && <button className="text-button" onClick={() => props.navigate(`/settings/runtimes?account=${encodeURIComponent(notice.accountId!)}&login=1`)}>Log in</button>}</p>)}
    <WhyMemory memory={decision.memory}/><h3>Corrections used</h3>{!decision.correctionsShown.length ? <p>None</p> : !corrections ? <p>Loading corrections…</p> : decision.correctionsShown.map((id) => { const correction = corrections.find((entry) => entry.id === id); return <div className="why-correction" key={id}>{correction ? <><p><strong>{correction.schema === 'composer-override-v1' && correction.request.value === null ? 'Back to Auto' : { once: 'Next decision only', pin: 'Keep for this conversation', noted: 'Just override', redo: 'Override and undo' }[correction.request.mode]}</strong> · {correction.changes.map((change) => `${change.field}: ${change.from === null ? 'Auto' : change.field === 'model' ? modelLabel(change.from) : change.from} → ${change.to === null ? 'Auto' : change.field === 'model' ? modelLabel(change.to) : change.to}`).join(', ')}</p><p className="muted small-text">{correction.context}</p></> : <p>This earlier correction is unavailable.</p>}</div>; })}
    {decision.account && <><h3>Account</h3>{decision.account.ranking.map((entry) => <p key={entry.accountId}>{accountLabel(entry.accountId)}: {entry.reason}{entry.accountId === decision.account?.chosen ? ' · selected' : ''}</p>)}</>}
    <h3>Jev</h3>{decision.jev ? <><p>{decision.jev.returnedModel} · {decision.latencyMs} ms</p>{decision.jev.records?.map((call, index) => <p className="muted small-text" key={index}>{call.kind === 'action' ? 'Next step' : call.kind === 'model' ? 'Model and effort' : 'Memory'} · {call.returnedModel} · {call.usage.input_tokens + call.usage.output_tokens} tokens · {call.latencyMs} ms</p>)}</> : <p>{decision.action.source === 'manual' || decision.action.source === 'redo' ? 'This step was picked manually.' : 'No Jev call was needed for this choice.'}</p>}
    <p className="muted small-text">{dateTime(decision.at)}</p>
  </Modal>;
}
