import { clientId } from './client-id.js';
import { useEffect, useState } from 'react';
import { z } from 'zod';
import { ConfigHistorySchema, ConfigPreviewSchema, ConfigRevisionSchema, type Configuration } from '@jevellan/core/client';
import { api } from './api.js';
import { JevConnection } from './jev-connection.js';
import { SectionHeading, dateTime, useTask, type PageProps } from './components.js';

export function ConfigurationPage(props: PageProps) {
  const [history, setHistory] = useState<z.infer<typeof ConfigHistorySchema>['revisions']>([]); const [yaml, setYaml] = useState<string>(); const [importing, setImporting] = useState(false); const [source, setSource] = useState(''); const [preview, setPreview] = useState<z.infer<typeof ConfigPreviewSchema>>(); const task = useTask(props.onError);
  useEffect(() => { void api('/hub/config/history', ConfigHistorySchema).then((result) => setHistory(result.revisions.reverse())).catch(props.onError); }, [props.data.config.revision, props.onError]);
  return <><SectionHeading title="Configuration"><div className="actions"><button className="secondary" onClick={() => void task.run(async () => { if (yaml !== undefined) { setYaml(undefined); return; } const response = await fetch('/hub/config/export', { credentials: 'same-origin' }); if (!response.ok) throw new Error('Configuration could not be loaded.'); setYaml(await response.text()); })}>{yaml === undefined ? 'View YAML' : 'Hide YAML'}</button><a className="button-link secondary" href="/hub/config/export" download="apm.yml">Export</a><button onClick={() => setImporting(true)}>Import</button></div></SectionHeading>
    <p className="intro">One configuration for every device. Each saved change creates a revision.</p>
    {yaml !== undefined && <section className="card"><h2>Current YAML</h2><pre>{yaml}</pre></section>}
    {importing && <section className="card"><h2>Import configuration</h2><form onSubmit={(event) => { event.preventDefault(); void task.run(async () => setPreview(await api('/hub/config/import-preview', ConfigPreviewSchema, 'POST', { schema: 'config-import-v1', yaml: source }))); }}><label>YAML<textarea required rows={10} className="code-editor" value={source} onChange={(event) => { setSource(event.target.value); setPreview(undefined); }}/></label><div className="actions"><button disabled={task.busy}>Validate and show diff</button><button className="secondary" type="button" onClick={() => { setImporting(false); setPreview(undefined); }}>Cancel</button></div></form>
      {preview && <div className="import-preview"><h3>{preview.changedPaths.length ? 'Changes to apply' : 'No changes'}</h3><ul>{preview.changedPaths.map((path) => <li key={path}><code>{path}</code></li>)}</ul><div className="diff-columns"><div><h4>Current</h4><pre>{preview.before}</pre></div><div><h4>Imported</h4><pre>{preview.after}</pre></div></div><button disabled={task.busy || !preview.changedPaths.length} onClick={() => void task.run(async (signal) => { await api('/hub/config', ConfigRevisionSchema, 'PUT', { schema: 'config-write-v1', revision: preview.revision, configuration: preview.configuration, clientRequestId: `config_${clientId()}` }, { signal, waitForHub: true }); setPreview(undefined); setImporting(false); setYaml(undefined); setSource(''); await props.reload(signal); props.message('Configuration imported.'); })}>Apply import</button></div>}
    </section>}
    <section className="card"><h2>Revisions</h2><div className="revision-list">{history.map((revision) => <div key={revision.revision}><strong>Revision {revision.revision}</strong><span>{dateTime(revision.at)}</span><span className="muted">{props.data.devices.devices.find((device) => device.id === revision.changedBy.deviceId)?.name ?? revision.changedBy.deviceId} · {revision.changedBy.source === 'ui' ? 'Settings' : revision.changedBy.source}</span></div>)}</div></section>
  </>;
}
export function DecisionsPage(props: PageProps) {
  const [draft, setDraft] = useState<Configuration>(() => structuredClone(props.data.config.configuration)); const task = useTask(props.onError); const config = draft['x-jevellan'];
  const change = (update: (value: Configuration['x-jevellan']) => void) => setDraft((current) => { const next = structuredClone(current); update(next['x-jevellan']); return next; });
  const available = props.data.offered.flatMap((offered) => offered.models.map((model) => ({ ...model, runtime: offered.runtime }))).filter((model) => !config.menu.some((entry) => entry.runtime === model.runtime && entry.model === model.id));
  return <><SectionHeading title="Decisions"/><p className="intro">Jev chooses each next step from the models and guidance you give it.</p>
    <JevConnection {...props}/>
    <form onSubmit={(event) => { event.preventDefault(); void task.run((signal) => props.saveConfig(draft, signal)); }}>
      <section className="card"><h2>Model menu</h2><label className="compact-label">Jev model<input required value={config.decisions.model} onChange={(event) => change((value) => { value.decisions.model = event.target.value; })}/></label>
      {config.menu.map((model, index) => <div className="menu-model" key={model.id}><div className="menu-model-heading"><label className="toggle"><input type="checkbox" checked={model.enabled} disabled={Boolean(model.unavailableReason)} onChange={(event) => change((value) => { value.menu[index]!.enabled = event.target.checked; })}/><span>Enabled</span></label><label>Label<input required value={model.label} onChange={(event) => change((value) => { value.menu[index]!.label = event.target.value; })}/></label><div><span className="muted">{model.runtime}</span><code>{model.model}</code></div></div><p className="muted small-text">Supported efforts: {model.efforts.join(', ')}{model.unavailableReason && ` · ${model.unavailableReason}`}</p><label>Description<textarea required rows={2} value={model.description} onChange={(event) => change((value) => { value.menu[index]!.description = event.target.value; })}/></label></div>)}
      {available.length > 0 && config.menu.length < 19 && <label>Add an offered model<select value="" onChange={(event) => { const offered = available[Number(event.target.value)]; if (!offered) return; change((value) => { value.menu.push({ id: `model_${clientId().replaceAll('-', '')}`, runtime: offered.runtime, model: offered.id, label: offered.label, description: 'Describe when this model fits the work.', efforts: offered.efforts, enabled: true }); }); }}><option value="" disabled>Choose a model</option>{available.map((model, index) => <option key={`${model.runtime}/${model.id}`} value={index}>{model.label} · {model.runtime}</option>)}</select></label>}
      </section>
      <section className="card"><h2>Effort guide</h2>{Object.entries(config.effortGuide).map(([effort, description]) => <label key={effort} className="effort-line"><span>{effort}</span><input required value={description} onChange={(event) => change((value) => { value.effortGuide[effort as keyof typeof value.effortGuide] = event.target.value; })}/></label>)}</section>
      <section className="card"><h2>Routing profile</h2><label><span className="sr-only">Routing profile</span><textarea required rows={12} value={config.routingProfile} onChange={(event) => change((value) => { value.routingProfile = event.target.value; })}/></label></section>
      <section className="card"><h2>Guards</h2><div className="form-grid">{([['maxStretchesPerWork', 'Stretches per work'], ['stretchTimeoutMin', 'Stretch timeout (minutes)'], ['reviewCap', 'Review cap'], ['noProgressLimit', 'No-progress limit'], ['testFailureLimit', 'Test failure limit'], ['externalActivityWindowMin', 'External activity window (minutes)']] as const).map(([field, label]) => <label key={field}>{label}<input type="number" min={field === 'reviewCap' ? 0 : 1} required value={config.guards[field]} onChange={(event) => change((value) => { value.guards[field] = Number(event.target.value); })}/></label>)}<label>Work cost cap (USD)<input type="number" min="0.01" step="0.01" placeholder="No cap" value={config.guards.workCostCapUsd ?? ''} onChange={(event) => change((value) => { value.guards.workCostCapUsd = event.target.value ? Number(event.target.value) : null; })}/></label></div><label className="toggle"><input type="checkbox" checked={config.guards.pauseAfterPlan} onChange={(event) => change((value) => { value.guards.pauseAfterPlan = event.target.checked; })}/>Pause after a plan</label></section>
      <div className="sticky-actions"><span className="muted">Saving creates a configuration revision.</span><button disabled={task.busy}>{task.busy ? 'Saving…' : 'Save decisions settings'}</button></div>
    </form>
  </>;
}
export function AboutPage(props: PageProps) {
  return <><SectionHeading title="About"/><section className="card"><h2>Jevellan</h2><p>Autonomous development, coordinated.</p><p className="muted">Version {props.data.devices.devices.find((device) => device.id === props.data.devices.currentDeviceId)?.version}</p><button className="secondary" onClick={() => props.navigate('/setup')}>Open setup guide</button><h3>Update</h3><code>jevellan update</code><h3>Uninstall</h3><code>jevellan uninstall</code></section></>;
}
